
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WS.sid.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "compteList", targetNamespace = "http://WS.sid.org/", className = "proxy.CompteList")
    @ResponseWrapper(localName = "compteListResponse", targetNamespace = "http://WS.sid.org/", className = "proxy.CompteListResponse")
    @Action(input = "http://WS.sid.org/BanqueService/compteListRequest", output = "http://WS.sid.org/BanqueService/compteListResponse")
    public List<Compte> compteList();

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://WS.sid.org/", className = "proxy.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://WS.sid.org/", className = "proxy.GetCompteResponse")
    @Action(input = "http://WS.sid.org/BanqueService/getCompteRequest", output = "http://WS.sid.org/BanqueService/getCompteResponse")
    public Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @param montant
     * @return
     *     returns java.lang.Double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convert", targetNamespace = "http://WS.sid.org/", className = "proxy.Convert")
    @ResponseWrapper(localName = "convertResponse", targetNamespace = "http://WS.sid.org/", className = "proxy.ConvertResponse")
    @Action(input = "http://WS.sid.org/BanqueService/convertRequest", output = "http://WS.sid.org/BanqueService/convertResponse")
    public Double convert(
        @WebParam(name = "montant", targetNamespace = "")
        Double montant);

}
